CREATE TABLE "YouGov Labour" (
    "Date" DATE,
    "Health" FLOAT,
    "Immigration & Asylum" FLOAT,
    "Crime" FLOAT,
    "The economy" FLOAT,
    "Tax" FLOAT,
    "Pensions" FLOAT,
    "Education" FLOAT,
    "Family life & childcare" FLOAT,
    "Housing" FLOAT,
    "The environment" FLOAT,
    "Britain leaving the EU" FLOAT,
    "Transport" FLOAT,
    "Welfare benefits" FLOAT,
    "Defence and security" FLOAT,
    "None of these" FLOAT,
    "Don't know" FLOAT,
    "Afghanistan" FLOAT,
    "Defence and Terrorism" FLOAT,
    "Don't know / None of these" FLOAT,
    "Unweighted base" FLOAT,
    "Base" FLOAT
);